apiVersion: apps/v1
kind: Deployment
metadata:
  name: renthere-backend
  labels:
    app: renthere-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: renthere-backend
  template:
    metadata:
      labels:
        app: renthere-backend
    spec:
      containers:
      - name: backend-container
        image: singhnikhil212/renthere-backend:latest
        ports:
        - containerPort: 5000
        envFrom:
        - secretRef:
            name: renthere-secrets
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
